### PR TITLE
Add Data Landing Zone Subs to Storage Firewall

### PR DESCRIPTION
**Pull request by marvinbuss**
## Summary of the Pull Request
This PR adds resource rules for all Data Landing Zone subcriptions to the Data Lakes. This allows cross-Data Landing Zone data access using SQL Pools and SQL serverless within DMA. It also fixes a few Bicep linting issues.

## References
None

## PR Checklist
* [x] Closes Issue https://github.com/Azure/data-landing-zone/issues/219
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA

## Validation Steps Performed
See comments and runs below.

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by marvinbuss** [comment]
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-landing-zone%2Fmarvinbuss%2Fadd_dlz_subscriptions%2Finfra%2Fmain.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-landing-zone%2Fmarvinbuss%2Fadd_dlz_subscriptions%2Fdocs%2Freference%2Fportal.dataLandingZone.json)

**Comment by marvinbuss** [comment]
Resource Access rules are correctly set. See image below:
image

**Review by amanjeetsingh — APPROVED** [review]
Good to go

**Pull request merged**
