### PR TITLE
Updated Portal UI based on Feedback

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
This PR fixes https://github.com/Azure/data-landing-zone/issues/212

### CODE REVIEW

**Comment by marvinbuss** [comment]
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-landing-zone%2Fmarvinbuss%2Fportal_updates%2Finfra%2Fmain.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-landing-zone%2Fmarvinbuss%2Fportal_updates%2Fdocs%2Freference%2Fportal.dataLandingZone.json)

**Comment by marvinbuss** [comment]
@mboswell Please test the link above and provide feedback!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by mboswell** [comment]
@marvinbuss this isn't a LGTM - the issue is still open and we need to resolve before this PR is merged.

**Comment by marvinbuss** [comment]
> @marvinbuss this isn't a LGTM - the issue is still open and we need to resolve before this PR is merged.

This will not get merged yet. Review is still pending.

**Review by amanjeetsingh — APPROVED** [review]

**Pull request merged**
