### PR TITLE
Improving Region Availability

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
* Improving ESA Region Availability

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by amanjeetsingh** [comment]
As a pre-deployment check, based on region and services selected in a template, we can do a scan if all chosen services are available in a region. If there's a service (or services) not available in chosen region, we can raise an error and fail deployment early.

**Comment by marvinbuss** [comment]
> As a pre-deployment check, based on region and services selected in a template, we can do a scan if all chosen services are available in a region. If there's a service (or services) not available in chosen region, we can raise an error and fail deployment early. User can then take an appropriate action before retrying.

I would rather limit the available options in the Portal and make sure users cannot even select certain regions. I think that is a better experience than a failed deployment.

**Comment by amanjeetsingh** [comment]
> > As a pre-deployment check, based on region and services selected in a template, we can do a scan if all chosen services are available in a region. If there's a service (or services) not available in chosen region, we can raise an error and fail deployment early. User can then take an appropriate action before retrying.
> 
> I would rather limit the available options in the Portal and make sure users cannot even select certain regions. I think that is a better experience than a failed deployment. Which API would you use?

Sure that could be an option but that means that we are choosing an option that might prohibit adoption in certain regions versus the others. Let's chat about the options next week. Personally, I want to avoid hard-coding regions. I def want to talk through this before committing to an approach.

**Comment by amanjeetsingh** [comment]
I have put together a PowerShell script to list regions which have all services available. 
Decision is -  do we go down the path where we restrict deployment to selected regions **OR** we include a pre-deployment check (using the script) to flag if a user tries to deploy in a region where one or more services aren't available.  Let's chat next week :) @marvinbuss

**Comment by marvinbuss** [comment]
Thanks @amanjeetsingh !
I strongly believe that we need to integrate this into the existing experience. Users will most likely not go and execute another PowerShell script to check region availability before they get started.

**Comment by amanjeetsingh** [comment]
> Thanks @amanjeetsingh ! I strongly believe that we need to integrate this into the existing experience. Users will most likely not go and execute another PowerShell script to check region availability before they get started.

Sent you a draft on potential options. We discuss; agree on an approach (manual or otherwise) and move forward.

**Comment by marvinbuss** [comment]
Closing this because of new PR and outdated branch.

**Pull request closed without merging**
